### ISSUE TITLE
Broken interpretation of try catch blocks using TryCatch package 

### ISSUE THREAD

**Issue by fieteboerner** [hurricup/Perl5-IDEA#1043]
By using the `try` `catch` statements of the `TryCatch` package, the code will not interpreted properly.

lint:
The plugin shows an error at the first `catch` statement: 
`Unable to find sub definition. declaration. constant definition or typeglob aliasing`

syntax:
All further `catch` blocks will be ignored in sytax highlighting and code linting.

indentation:
The code from `try` opening brace until first `catch` closing brace will be indented faulty. (one indentation level to much)

Single catch block (broken):
![single_catch_blocks_broken](https://cloud.githubusercontent.com/assets/8209685/14581212/0e33fbae-03e7-11e6-830a-3225429c0658.png)
should look like:
![single_catch_blocks_nice](https://cloud.githubusercontent.com/assets/8209685/14581214/0e378440-03e7-11e6-9cfd-a00408ba9f6b.png)
Multiple catch blocks (broken):
![multiple_catch_blocks_broken](https://cloud.githubusercontent.com/assets/8209685/14581213/0e3696e8-03e7-11e6-8753-6d532af4fe98.png)
should look like:
![multiple_catch_blocks_nice](https://cloud.githubusercontent.com/assets/8209685/14581215/0e399a0a-03e7-11e6-9164-d76e8eadfaa1.png)

I have used the following code:

trycatch.pl

```perl
#! /usr/bin/perl

use strict;
use warnings;

use TryCatch;
require 'BaseException.pm';

try {
    #    die { message => "something failded" };
    die BaseException->new( message => "something failded" );
} catch( BaseException $exception ) {
	print $exception->getMessage();
} catch (BaseException $exception){
    print $exception->{message};
} catch (BaseException $exception){
    print $exception->{message};
}
```

BaseException.pm

```perl
use strict;
use warnings;

package BaseException;

sub new{
	my $class = shift;
	my %params = @_;

	my $this = {
		code => $params{'code'} || -1,
		message => $params{'message'} || '',
	};
	bless $this, $class;

	return $this;
}

sub getMessage {
	my $this = shift;

	return $this->{message};
}

sub getCode {
	my $this = shift;

	return $this->{code};
}

1;
```

**Comment by hurricup** [comment]
No try-catch sytax is supported atm.

**Comment by hurricup** [comment]
I guess some light version with catch{} and catch($err){} won't be hard to support.

**Comment by fieteboerner** [comment]
It works perfectly. Thanks a lot.

**Comment by hurricup** [comment]
You may update and rebuild or fetch http://evstigneev.com/IDEA-Perl5-1.423.zip
Added some live-templates and completion
