### ISSUE TITLE
out of memory on file with syntax errors

### ISSUE THREAD

**Issue by dirtyequi** [hurricup/Perl5-IDEA#1070]
Hi,

please open the attached perl script in IntelliJ. You may notice that Java tries to allocate RAM until the Xmx value has reached. 
Although the perl syntax is never valid, this should be considered a bug.

Thank you

[test.txt](https://github.com/hurricup/Perl5-IDEA/files/234891/test.txt)

**Comment by hurricup** [comment]
What plugin version, what JB product and version, what Java version?

**Comment by hurricup** [comment]
Works for me: http://joxi.net/J2beb0kF4RQn4m.png

**Comment by dirtyequi** [comment]
- JB intelliJ IDEA 2016.1.1
- Perl Camelcade 1.402
- JRE (bundled with intelliJ) 1.8.0_76_release-b18 (openJDK)
- OS: Ubuntu 16.04 LTS

still does not work for me

**Comment by hurricup** [comment]
Could you try new version RC build? http://evstigneev.com/IDEA-Perl5-1.431.zip

**Comment by dirtyequi** [comment]
works perfectly now, thank you
