### ISSUE TITLE
*.html as *.mas

### ISSUE THREAD

**Issue by almirus** [hurricup/Perl5-IDEA#1075]
Hi! Please add option for parsing *.html (or any files with any extensions) files as *.mas or manual marking any files as HTML::Mason

**Comment by hurricup** [comment]
It's in there: http://joxi.net/12MBzPEI4QaGoA.jpg

**Comment by almirus** [comment]
but doesn't for for me http://i78.fastpic.ru/big/2016/0426/aa/1b4064f93417e261bb6386aa4c6811aa.png

**Comment by almirus** [comment]
Thanks! I found the problem - it was necessary to add "Components roots"
Please close issue

**Comment by hurricup** [comment]
Yep, as it's said: only under roots configured above :)
