### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by almirus** [hurricup/Perl5-IDEA#1077]
hi! this string `<b><% $boomerang_sum  %>%</b>` in mason component, supposedly contains an error "Unexpected token"
next is another strange (tooltip)
http://i79.fastpic.ru/big/2016/0426/7f/86d1a996db270cf3b21251f8a6618b7f.png

**Comment by hurricup** [comment]
I'll check into this. Could you please run code analysis on all your sources and provide full list of found errors. Here, or to my email hurricup@gmail.com
Next release will come in few days, would be nice to fix them all.

**Comment by hurricup** [comment]
Please, try http://evstigneev.com/IDEA-Perl5-1.432.zip
