### ISSUE TITLE
Invalid command order when executing perl for intellij

### ISSUE THREAD

**Issue by t6jin** [hurricup/Perl5-IDEA#1090]
In intellij, before version 1.5, the program arguments are added after the perl script. For example if the script is something like [/path/to/my/perl.pl] and the program arguments are something like "-v --preserve", then when the script is executed in intellij, the whole command will be like perl [/path/to/my/perl.pl] -v --preserve.

However after the update, the program arguments are inserted between the perl keyword and the perl script, so the whole command is like perl  -v --preserve [/path/to/my/perl.pl] , therefore, the perl script won't be executed at all.

Perl Plugin Version: 1.5
Intellij Version: 
IntelliJ IDEA 2016.1.1
Build #IC-145.597, built on March 29, 2016
JRE: 1.8.0_40-release-b132 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by hurricup** [comment]
You may try http://evstigneev.com/IDEA-Perl5-1.501.zip
