### ISSUE TITLE
Can't find declaration of exported variables

### ISSUE THREAD

**Issue by Suic** [hurricup/Perl5-IDEA#1096]
If variable was imported to local namespace using Exporter module idea highlights this variable as non declared.
Example:
file Foo.pm
```
package Foo;
use strict;
use warnings;
use Exporter; 
our @ISA  = ('Exporter');
our @EXPORT = qw/$MYVAR/;
our $MYVAR = 'test';
1;
```

file Bar.pm
```
package Bar;
use strict;
use warnings;
use Foo;
my $test = $MYVAR;        <----Here $MYVAR is highlighted as non declared variable
1;
```

**Comment by hurricup** [comment]
Try to remove quotes in our `@EXPORT = qw/'$MYVAR'/;`
QW is quoting for you

**Comment by Suic** [comment]
Sorry for misleading you. There no quotes in my actual code, but problem still exists.
I've edited issue description

**Comment by despertargz** [comment]
Warning happens also when explicitly importing symbols 

```
package Foo;
our @EXPORT_OK = qw( $MYVAR ); 
```

```
package Bar;
use Foo qw( $MYVAR)
```

**Comment by hurricup** [comment]
Please, try http://evstigneev.com/IDEA-Perl5-1.503.zip
