### ISSUE TITLE
Package variables are parsed incorrectly

### ISSUE THREAD

**Issue by almirus** [hurricup/Perl5-IDEA#1121]
Hi!

![1](https://cloud.githubusercontent.com/assets/16898685/15039501/4da493c4-12b6-11e6-8811-0ff3980db31f.png)

![2](https://cloud.githubusercontent.com/assets/16898685/15039381/4a5ee9c2-12b5-11e6-9a11-beeceb879f90.png)

http://perldoc.perl.org/functions/package.html
http://perldoc.perl.org/perlmod.html#Packages

**Comment by hurricup** [comment]
https://github.com/hurricup/Perl5-IDEA/wiki/Perl-syntax-nuances

> our  variables should be declared at least once. You may refer them later as $package::var, but to make re-factoring works properly you must declare them somewhere.

**Comment by almirus** [comment]
sorry,my miss
