### ISSUE TITLE
Feature request: recognizes exported variables

### ISSUE THREAD

**Issue by wang-q** [hurricup/Perl5-IDEA#1154]
Hi.

When creating scripts running as command line tools, `$FindBin::RealBin` is frequently used. But it isn't recognized by Perl5-IDEA.

![screen shot 2016-05-09 at 21 48 07](https://cloud.githubusercontent.com/assets/6592693/15115088/cf603536-162f-11e6-818b-dee955050839.png)

I'm using version 1.505 of Perl5-IDEA.

(Thanks for your great working on this awesome plugin.)

**Comment by hurricup** [comment]
It's recognized, but if you'll check FindBind - there are no explicit declarations of variables using our or use vars. Atm such usage is not supported and i'm not sure it will ever be. 

https://github.com/hurricup/Perl5-IDEA/wiki/Perl-syntax-nuances

**Comment by akarelas** [comment]
@hurricup Couldn't you execute perl during indexing with the same `use FindBin '$RealBin';` line that was found in the source file, to see what variables and other symbols are exported?
