### ISSUE TITLE
Perl::Critic failed to start and has been disabled

### ISSUE THREAD

**Issue by mtfz** [hurricup/Perl5-IDEA#1161]
Make sure that Perl::Critic module is installed
perlcritic (or perlcritic.bat on Windows) starts successfully from the command line
Mac users must explicitly configure PerlCritic executable in Perl5 settings
Re-enable it in Perl5 Settings tab

**Comment by hurricup** [comment]
I know this message, I wrote it, than you. What is your report about? What system, perl, IDE, versions of all of them, what are you doing and what is going on?

**Comment by despertargz** [comment]
Hello, I also have this issue, here is some more information:

os version: Linux mev.pc 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
perl version: v5.16.3

IntelliJ Version:
IntelliJ IDEA 2016.1.1
Build #IC-145.597, built on March 29, 2016
JRE: 1.8.0_76-release-b18 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Steps to Reproduce:
> Click Settings
> Languages & Frameworks 
> Perl5 settings 
> check ‘Enable Perl::Critic:: annotations (should be installed)

Am able to run perlcritic from any commandline:
~ $ perlcritic test.pl
Code before strictures are enabled at line 1, column 1.  See page 429 of PBP.  (Severity: 5)


Similar issue with perl Tidy - You probably would like this in its own issue, just let me know.
Steps to reproduce:
Click Code > Re-format with Perl::Tidy
Error: "Cannot run program "perltidy" (in directory"/home/mev/repos/myproject"):error=2, No such file or directory"

**Comment by mtfz** [comment]
I'm facing these issues with Windows 10 OS too.


Whereas having more or less same configuration of jetBrain.
