### ISSUE TITLE
Feature Request - annotate variable types

### ISSUE THREAD

**Issue by dezzak** [hurricup/Perl5-IDEA#1164]
Perhaps I'm missing something, but I can't seem to find a way to tell the IDE what type a variable is.

For example, I'm wanting to do something similar to this, but can't seem to figure out how...

```perl
#@var Some::Widget::Module[]
$self->{widgets} = [];
```

and/or later

```perl
#@var Some::Widget::Module $widget
foreach my $widget ( @{ $self->{widgets} } ) {
    # ... $widget is recognised as being a Some::Widget::Module
}
```

If this (or some similar feature) is present, perhaps just the documentation needs clarifying. Alternatively, it's entirely possible that I'm Doing It Wrong™ - if so, how should I be doing it?

Thanks

**Comment by hurricup** [comment]
http://perldoc.perl.org/functions/my.html

https://github.com/hurricup/Perl5-IDEA/wiki/Perl-syntax-nuances
> Camelcade actively using type in variable declaration: my Foo::Bar $foo_bar_object. Types helps to resolve methods.

In your case you may use: 

```
foreach my Some::Widget::Module $widget ( @{ $self->{widgets} } ) {
    # ... $widget is recognised as being a Some::Widget::Module
}
```

However, it won't work with hash elements without intermediate variable.

**Comment by dezzak** [comment]
Ah ha!, not come across that notation before, and must have missed it in the docs.

Thanks :-)
