### ISSUE TITLE
Unable to find existing packages

### ISSUE THREAD

**Issue by nick2012** [hurricup/Perl5-IDEA#1178]
Hi,

The pl file contains something like:

```
use lib 'I:/mylib/';
use MyHTML;
```
MyHTML.pm is in I:/mylib/

However IntelliJ reports that it's unable to find MyHTML package.

What am I doing wrong?

**Comment by hurricup** [comment]
Looks like a bug in the last version. For now you may use a symlink to your project directory and mark it as libraries using project settings
