### ISSUE TITLE
Debugger messes up SQLite DBD handle

### ISSUE THREAD

**Issue by mradile** [hurricup/Perl5-IDEA#1193]
I am using DBD::SQLite in my code with "PRAGMA foreign_keys =1". 

When using the Debugger (remote debugging a script) the following statements fail:

```
$dbh->do("PRAGMA foreign_keys = 1"); 
my $res = $dbh->selectall_arrayref("PRAGMA foreign_keys");
unless ($res && $res->[0] && !empty($res->[0]->[0])) {
    die "Failed!";
}
```

**Comment by hurricup** [comment]
Any watches are active?

**Comment by hurricup** [comment]
Moved to the debugger tracker: https://github.com/hurricup/Perl5-IDEA-Debugger/issues/9
