### ISSUE TITLE
Can't start IntelliJ IDEA 14.1.4

### ISSUE THREAD

**Issue by KaraBudda** [hurricup/Perl5-IDEA#158]
Windows 7x64/

IntelliJ IDEA 14.1.4 Ultimate

IDEA's crashing on start:
Cannot load project: com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: com.perl5.lang.perl.idea.components.PerlProjectComponent PluginClassLoader[com.perl5, 0.28 beta] [Plugin: com.perl5]

Should I use some specific version of IDE?

**Comment by hurricup** [comment]
Nope, guess it's something local. Started development with 13.xxx, now got 14.1.4 ult, and few my collegues use current community. Never seen such error.

**Comment by KaraBudda** [comment]
How could I get some more information about error?

**Comment by hurricup** [comment]
Well, the only way I know is to clone this repo, compile plugin yourself and try to run it in debugging mode. I can't reproduce this problem.
May be there is a kinda conflict with some other plugin? You could try to start plugin without others and if it will start, find the conflict by enabling usual plugins one by one. Than i'll be able to do the same on my side.

**Comment by KaraBudda** [comment]
Disabled all plugins except Camelcade. Everything's OK.
Enabled plugins I need. Everything's still OK.

Thank you. Will tell you if I find what plugin coflicts with Camelcade.
