### ISSUE TITLE
Mason Support

### ISSUE THREAD

**Issue by themanifold** [hurricup/Perl5-IDEA#235]
Would you consider supporting Mason?

**Comment by hurricup** [comment]
I don't know much about Mason, but planning to implement all major frameworks/templates support. Just a question of free time and amount of necessary changes.
if you could contact me via Skype, for example and share your vision of support, i could give you more concrete estimates.

**Comment by jpletcher** [comment]
+1 for Mason support.

I'd like to help, or at least try to, build very minimal syntax highlighting support for Mason.
Mason is many things, but basically it's a template engine, similar to embedded Perl5 or PHP.

Could you outline a few areas where I would begin looking to bring in Mason support?

**Comment by hurricup** [comment]
Would http://search.cpan.org/~jswartz/Mason-2.24/lib/Mason/Manual/Syntax.pod be enough for start?

**Comment by jpletcher** [comment]
Thanks, actually I was looking for help on how you would design this in your plugin.

I was considering creating a com.perl5.lang.mason package, to sort-of mirror the existing embedded package.  What sort of classes / interfaces would I minimally have to implement?

**Comment by hurricup** [comment]
Well, basically you need to duplicate mojo package and adjust lexer to capture Mason markers. But it's basically :)
First impression from Manual::Syntax is that Mason is more like Mojo, than php (or embedded perl)
If you want to try yourself, add me to skype (hurricup) so you could ask questions.

**Comment by themanifold** [comment]
I use mason at work quite alot, so I would be willing to test drive/bug report any implementations. As for actual support, the best start would probably be valid syntax highlighting. I've not actually found any application that could do it properly. Vim tries hard, but often gets muddled up. Eclipse just treats the code like perl, which is no good.

**Comment by jpletcher** [comment]
Great thanks, I think when I last looked at this you had not implemented mojo yet.  I'll take a look at that.

**Comment by hurricup** [comment]
Okay, small investigation shown that it's not possible to implement Mason the same way as Mojo, because it's more complicated. But, i've got an idea how to make a parser-extension mechanism.

**Comment by aleksandrpanteleymonov** [comment]
+1 for Mason

**Comment by hurricup** [comment]
Locked by #542 
Locked by #528

**Comment by Suresh301190** [comment]
+1 for mason

**Comment by hurricup** [comment]
Ok. Blocking tasks has been closed
Basic R&D been done, see the https://github.com/hurricup/Perl5-IDEA/labels/Mason
This issue has been resolved, see decomposed tasks

**Comment by hurricup** [comment]
OK, daily build with Mason support available. Please test it intensively. I can't do it myself good enough, because not using it in my work. https://twitter.com/CamelcadeIDE/status/685910261287546881

**Comment by hurricup** [comment]
To make things clearer, which Mason you've requested: HTML::Mason (Mason1) or Mason2 ?

**Comment by jpletcher** [comment]
Actually, I guess we use mason 1.  I was not aware there is a newer
iteration.

This is a great start though. And better Than anything I've had before.

I will have to double check the components root issue, but I'm fairly
certain it was included. All files had that ' not included ' message.

**Comment by hurricup** [comment]
Well, it seems to me that everone wanted to have Mason 1, but searching for perl Mason lead me to Mason 2 and I've implemented it. So this is gonna be my best failure in last few years :)
