### ISSUE TITLE
Unnecessary read action wrapping inside completion providers

### ISSUE THREAD

**Issue by VISTALL** [hurricup/Perl5-IDEA#258]
Hi. 

You dont need wrap it, into read actions

https://github.com/hurricup/Perl5-IDEA/blob/bd56aa95bb559025655b48da439cf98eba39b538/src/com/perl5/lang/perl/idea/completion/providers/PerlPackageBuiltInCompletionProvider.java#L37

https://github.com/hurricup/Perl5-IDEA/blob/bd56aa95bb559025655b48da439cf98eba39b538/src/com/perl5/lang/perl/idea/completion/providers/PerlPackageCompletionProvider.java#L39

https://github.com/hurricup/Perl5-IDEA/blob/bd56aa95bb559025655b48da439cf98eba39b538/src/com/perl5/lang/perl/idea/completion/providers/PerlPackageSubCompletionProvider.java#L60

and others.

**Comment by hurricup** [comment]
Good point. Thank you!
