### ISSUE TITLE
Directory listing with wildcard error

### ISSUE THREAD

**Issue by Dethnull** [hurricup/Perl5-IDEA#329]
I may be stating what the problem is, incorrectly and I apologize in advance for that as I'm extremely new to perl. I'm using your plugin in my favorite editor to learn Perl. Also, keep up the awesome work!

The following statement is correct and I've seen it many times, but reports the error in the screenshot. I'm currently using version  0.38 beta.

    my @list = <*>;

<img width="1547" alt="screen shot 2015-08-13 at 9 54 47 pm" src="https://cloud.githubusercontent.com/assets/3405464/9267580/53c57a92-4206-11e5-8a7b-6dbbfa4719d7.png">

**Comment by hurricup** [comment]
You are missing quotes
http://perldoc.perl.org/functions/glob.html
