### ISSUE TITLE
Code->ReformatCode should call perltidy.

### ISSUE THREAD

**Issue by dimentox** [hurricup/Perl5-IDEA#382]
When asking intelij to reformat code it should use perltidy to do so. Also it seems we missing language settings in the main properties.

**Comment by hurricup** [comment]
There is no formatter yet and PerlTidy integration is planned, but as an additional option: https://github.com/hurricup/Perl5-IDEA/issues/209

**Comment by hurricup** [comment]
Duplicates #209
