### ISSUE TITLE
Implement processor for perl5i

### ISSUE THREAD

**Issue by Pilat66** [hurricup/Perl5-IDEA#405]
perl files with "use perl5i::2" : code inspector says "No strict pragma found in the file". But perl5i::2 contains Modern::Perl, "Modern::Perl turns on strict and warnings, enables all the 5.10 features like given/when, say and state, and enables C3 method resolution order." and using strict and use warnings enabled automatically

Minimal example:

    package test;
    use perl5i::2;

**Comment by hurricup** [comment]
This module requires specific handling. Thanks.
http://search.cpan.org/~mschwern/perl5i/lib/perl5i.pm

**Comment by hurricup** [comment]
According to http://matrix.cpantesters.org/?dist=perl5i+v2.13.1 it's not really enterrise solution
And according to https://metacpan.org/requires/distribution/perl5i?sort=[[2,1]] not wide-used.
So won't be implemented in nearest future, sorry.
