### ISSUE TITLE
Console filter polishing

### ISSUE THREAD

**Issue by hurricup** [hurricup/Perl5-IDEA#467]
1. Link should wrap all the path, not part of it from project's root till the end.
2. Paths like `dir/dir/../../dir/dir` are not handled properly
3. All path-like constructions should be checked for being a valid path, like test results: `t/somedir/test.t .. ok`

**Comment by eli1982** [comment]
fixed in d07a066d079c5ab9055439ba3ab87ace0c1f0e72
