### ISSUE TITLE
Hash character - # - in regexp interpreted as comment

### ISSUE THREAD

**Issue by ravn** [hurricup/Perl5-IDEA#497]
I have the following regular expression matching filenames containing hash characters - # - but is interpreted incorrectly by the IntelliJ perl plugin:

    if (m!/([A-Z]{3}[^/]+)[A-Z](\d.)#\d\d\d\d\.pdf$!) {	# desired PDF?

It is rendered as:

![image](https://cloud.githubusercontent.com/assets/117042/10280065/b0fda9d6-6b6a-11e5-8ffb-765d86ff5f2b.png)

Please advise.

**Comment by ravn** [comment]
![image](https://cloud.githubusercontent.com/assets/117042/10280058/a61a77c4-6b6a-11e5-999f-c1b7c02d3009.png)

**Comment by hurricup** [comment]
In few days will have a next version release, and seems it's ok in there:
http://joxi.ru/L21v6xQu4NX4AX.jpg
I can make a current build and put in to my download server if you wish.

**Comment by ravn** [comment]
Thank you for your prompt reply.  

I can wait for a few days for an official release , so no need to go to the trouble of providing a current build.  When the plugin has updated automatically I will check again and come back to this issue.

**Comment by hurricup** [comment]
As you wish. Thank you for report!
