### ISSUE TITLE
Enabling Camelcade in PHPStorm causes issues with the PHP autocomplete

### ISSUE THREAD

**Issue by wshafer** [hurricup/Perl5-IDEA#505]
Hello,

First thank you guys for adding Perl support to PHPStorm.  It has come in very handy.

With that said, I noticed that once you enable Camelcade the docblock autocomplete in PHP stops working.

To replicate:
** Open a php file.  Add the start of your comment block just above the function/method  ie. /**
** Press enter

Result:  Blank new line.

Expected:  Autocomplete should add the configured docblocks (@param, @return, @throws, etc)

System:
PHPStorm 9.0.2
Camelcade: 1.004
Mac OSX Yosemite 10.10.5

Thanks in advance,
Westin Shafer

**Comment by hurricup** [comment]
Seems this problem has been fixed in the next version, you may try release candidate: http://evstigneev.com/camelcade.jar

**Comment by wshafer** [comment]
Works great.  Thanks.
