### ISSUE TITLE
Curly brackets in subroutine attributs break formatting

### ISSUE THREAD

**Issue by wesley-harding** [hurricup/Perl5-IDEA#526]
When a subroutine attribute contains an unquotes curly bracket, the closing bracket is not properly detected and breaks.

Examples:

```
sub some_sub {
   # Correct
}


sub some_sub :SomeAttribute('foo') {
    # Correct
}

sub some_sub :SomeAttribute('foo/{bar}'){
   # Correct (because foo/{bar} is treated as a string
}

sub some_sub :SomeAttribute(foo/{bar}) {
   # Code highlighting broken for the rest of the script.  
}

# Real-world example
sub user_profile :REST(GET user/{id}) {
   # Code highlighting broken for the rest of the script.
}

```

I know this is probably a rather unique use case, so I certainly don't expect that this will be a high-priority fix.  I may try to fix it myself, but I need to learn the basics of Jetbrains plugins first.

**Comment by hurricup** [comment]
Current version (1.1009) parses this fine
Have you updated ?

**Comment by wesley-harding** [comment]
Look at that. It's fixed!

I just upgrade all of my packages on Monday (10/12) and it looks like this just got released yesterday (10/14).  I guess you managed to slip it in. This was a pleasant surprise and, honestly, I thought it would be such small issue that it would never get addressed.

Thank you!  

I'd be happy to drop you some beer money if you have a donation link.

**Comment by hurricup** [comment]
I've added one. you may try. (never used it before)
https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=HJCUADZKY5G7E

**Comment by hurricup** [comment]
If you've tried and failed - try again. Should work ok now. Thanks.

**Comment by wesley-harding** [comment]
Cool, I tried it earlier in the week and it didn't work.  I had it on my calendar to try this weekend, but you figured it out.

Based on US standards, that should be between 1-3 beers.
