### ISSUE TITLE
Add Support for PHPStorm 9+

### ISSUE THREAD

**Issue by christianklemp-imt** [hurricup/Perl5-IDEA#565]
Currently unable to install the plugin in PHPStorm through the built-in plugin browser or by downloading the plugin repo jar or the most current found in the readme. Verified on version 9.0.2.

**Comment by hurricup** [comment]
There should be the way to install version 1.111 from the JB repo. It's compatible with previous products versions (IDEA14 and PHPStorm 9). 
Please, note: no further versions will be released for outdated platforms, because only 1% of users has not upgraded, sorry.
