### ISSUE TITLE
use statement auto-completion hangs

### ISSUE THREAD

**Issue by klevin** [hurricup/Perl5-IDEA#574]
Description: IntelliJ hangs when typing "use" statements in perl code

How to reproduce: start typing "use IO::File" (or any other module, such as Getopt::Std). The IDE hangs as soon as the first character of the module name is typed. For instance, I get to "use I", and IntelliJ hangs.

OS name and version: Arch Linux 64bit

Java version: openjdk 7.u91_2.6.2

JetBrains product name and version: IntelliJ 15.0

Plugin version: 1.112

Priority: High

**Comment by hurricup** [comment]
I've had the same bug month ago. Please, try to Invalidate cache/restart. 
Couldn't locate the problem and it's just self-resolved :)

**Comment by klevin** [comment]
Invalidate cache/restart didn't help.

**Comment by hurricup** [comment]
Well, i can't intentionally reproduce the problem, so don't even know how to help you atm. Could you try Oracle Java instead of OpenJDK?

**Comment by klevin** [comment]
Haven't been able to try the Oracle JDK, yet. However, it appears to be related to the size of the project. The project I'm working on is rather large, with 112 Perl files (37080 lines), and 72 Python files (23342 lines) (along with corresponding amounts of Javascript and html). If I create a new, project, the Perl auto-completion doesn't cause IntelliJ to hang.

**Comment by hurricup** [comment]
Nope. I work myself with project about 5k files size daily. And plugin is being used and been tested on project with > 100k files
