### ISSUE TITLE
Modules not being detected relative to a project's library folder

### ISSUE THREAD

**Issue by StrikeForceZero** [hurricup/Perl5-IDEA#585]
Great plugin. Can't wait for the moose support. One thing that's been holding me back from actively using it. Curious if I'm expecting non intended functionality or if there is a bug.

Version: Intelij 15.1 (haven't tried any other of the jetbrains IDE's with this yet)
Latest in Repo and Development.jar possibly affected.

I could be doing something wrong but I have followed the [wiki's "getting started" step by step guide](https://github.com/hurricup/Perl5-IDEA/wiki/Getting-started).
In intellij 15 I don't see the library annotation as shown in the following image

 ![here](https://github.com/hurricup/Perl5-IDEA/raw/master/images/gettingstarted/finalstep.png)

Inside project structure its complaining that the library is not being used by any module. When you attempt to "fix the issue" by adding it as a dependency of one of your modules, it comes back after 3 seconds or so, as if it's never applying. Forcing it by adding it to the Module.iml doesnt work either.

I was expecting it to work without modifying the @INC given this statement:
> To let Camelcade search for package files, you should mark your lib directory as a library source (what you are doing with -I parameter of Perl interpreter).

> Remember, all packages being resolved relatively to one of the lib dirs: module or SDK-specific.

---
##### Folder layout

* lib/ *(no annotation...)*
   * MyBundle/
       * Foo/
           * Bar.pm *(required modifying the @INC to use MyBundle::Main)*
       * Main.pm *(can use MyBundle::Foo::Bar without modifying the @INC)*

**Comment by hurricup** [comment]
I need to update wiki for the most recent version. 
In the current IDEA/plugin library should look like: http://joxi.ru/v2943qaf7PK0mG.jpg

I've got some strange problems with migrating 14->15, re-creating module file helped. Just delete it and create Perl module from the scratch. 

Library path is now added using Libraries marker, not Dependencies tab, that should not be there at all : http://joxi.ru/l2Z14PbU0GX1mJ.jpg

**Comment by StrikeForceZero** [comment]
Awesome, setting the folder to library solved the issue. Still complains about unused library in the project structure page but at least I full resolution inside my library folder.

**Comment by hurricup** [comment]
I don't know what are you talking about. Have you re-created module?

**Comment by StrikeForceZero** [comment]
Sorry, hopefully this will help.

![image](http://i.imgur.com/qZVcFzi.png)

![image](http://i.imgur.com/jkSmCv6.png)

**Comment by hurricup** [comment]
Remove library from libraries section. This facility is not used by the plugin. Only marking in Module structure.

**Comment by StrikeForceZero** [comment]
ok thanks
