### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by elcamlost** [hurricup/Perl5-IDEA#61]
I downloaded zip version of plugin and tried to install it. IDEA crashed after restarting with this error

![21](https://cloud.githubusercontent.com/assets/5188593/7728828/07de41a6-ff1a-11e4-9da5-85079682aa2c.png)

Next, i forked repo and create IDEA plugin project. But project building failed because of dozens of errors.

```
Error:(6, 31) java: cannot find symbol
  symbol:   class PerlVisitor
  location: package com.perl5.lang.perl.psi
```
```
Error:(14, 32) java: cannot find symbol
  symbol:   class PodElementTypes
  location: package com.perl5.lang.pod.lexer
```
And 98 errors more...

Looks like github repo missing some files needed to complile plugin.

**Comment by hurricup** [comment]
First, you can't install it's from zip. It's dev project, need to be builded.
Second, project does not  containing files generated from flex and bnf. 
I'll add jar plugin shortly

**Comment by hurricup** [comment]
Try camelcade.jar

**Comment by elcamlost** [comment]
Great thanks. Now it's working!

And sorry for my issue. Now I see that I didn't understand problem well enough ((
