### ISSUE TITLE
PhpStorm 9.0.2 install fails

### ISSUE THREAD

**Issue by iowelinux** [hurricup/Perl5-IDEA#614]
Hi,

PhpStrom just downloads plugin from repository and doesn't install it.
http://scr.pics/15obm16.png
Nothing happens after download.

It's told the plugin is compatible with PhpStorm
https://plugins.jetbrains.com/plugin/7796?pr=phpStorm

Mac OS X 10.11

**Comment by hurricup** [comment]
See https://github.com/hurricup/Perl5-IDEA/issues/565
