### ISSUE TITLE
Implement Switch module support

### ISSUE THREAD

**Issue by norguhtar** [hurricup/Perl5-IDEA#658]
I'm use in my code switch statement. Now plugin show error on construction like this:

switch ($RAD_REQUEST{'Acct-Status-Type'}) {
		case 'Start' {
         } 
}

But code is fine and run with perl without problem.

Plugin on switch write this error:
Unable to find sub definition, declaration, constant definition or typeglob aliasing less... (Ctrl+F1) 
Check if sub has been defined, declared or aliased with a typeglob. NB (current development state issues):
Plugin can't resolve subs in chain calls and inherited subs.
Plugin can't reslove SUPER subs.
Plugin can't reslove imported subs.
Plugin can't resolve constant-generated subs or other generated properties.

**Comment by hurricup** [comment]
Where is this switch statement in http://perldoc.perl.org/perlsyn.html ?

**Comment by norguhtar** [comment]
I'm use switch module. I should use for?

**Comment by hurricup** [comment]
Every module introducing additional uncommon syntax should be supported explicitly. Atm plugin supports native Perl5 syntax and Method::Signatures::Simple extension.

**Comment by hurricup** [comment]
You may try today's daily build, should work fine http://evstigneev.com/camelcade.jar

**Comment by norguhtar** [comment]
Yep. Now parser work correct
