### ISSUE TITLE
Core libraries do not autopopulate

### ISSUE THREAD

**Issue by dezzak** [hurricup/Perl5-IDEA#691]
Hello!

First time using this plugin, so not sure if it is something I missed [in the documentation](https://github.com/hurricup/Perl5-IDEA/wiki/Getting-started:-specialized-IDEs-(PyCharm,-PHPStorm,-etc)) or a platform issue, or just me being a noob.

Platform is Debian 8, PHPStorm 10.0.2, using v1.218 of the plugin.
```
$ java -version
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-1~deb8u1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
```

Despite configuring the path to perl, and adding my own local lib folder for this project, none of the core modules (strict, warnings, etc.) are available. Is there some extra steps that I need to do? I note that the external libraries section is empty, and I suspect this is where the problem lies.

![screenshot from 2016-01-05 15 18 25](https://cloud.githubusercontent.com/assets/3330604/12119009/fed1e002-b3c0-11e5-992f-e99617f6f3a1.png)

The perl path is definitely correct:

```
$ which perl
/usr/bin/perl
```

Thanks in advance

**Comment by hurricup** [comment]
Crap, i need to do something with this. Put /usr/bin there. Without perl itself. Should work fine. When you click browse button, it allowes you to select only directories. Thanks for report!
