### ISSUE TITLE
Structure view broken in 1.3 dev builds within file with several classes

### ISSUE THREAD

**Issue by elcamlost** [hurricup/Perl5-IDEA#769]
Hello.  I've found change of behavior in structure view for files containing several packages. Attachments illustrates the problem.
dev build
![dev_build](https://cloud.githubusercontent.com/assets/5188593/12386798/f45ffd44-bdd8-11e5-8ebf-2cfb33395e4c.png)

stable build
![stable build](https://cloud.githubusercontent.com/assets/5188593/12386801/fdc08426-bdd8-11e5-9f62-9acd00798262.png)

**Comment by hurricup** [comment]
This is intended change in https://github.com/hurricup/Perl5-IDEA/issues/674
The point is that inner package may use lexical variables declared in outer one.

**Comment by hurricup** [comment]
Adjusted tree view back. New "ladder" was not really comfy.

**Comment by elcamlost** [comment]
Awesome.
We have file with 52 packages and nested ladder was not suitable in this strange situation.
