### ISSUE TITLE
Please add support for fields from Class::Accessor(::Fast)

### ISSUE THREAD

**Issue by nthykier** [hurricup/Perl5-IDEA#778]
Hi

Please consider adding support for fields/methods created via Class::Accessor / Class::Accessor::Fast.  In the following example, "field" should be considered a valid method.

```perl
package Foo;
use strict;
use warnings;

use parent qw(Class::Accessor::Fast);

Foo->mk_ro_accessors(
    qw(field)
);

sub test {
    my ($self) = @_;
    return $self->field;
}

1;
```

**Comment by hurricup** [comment]
I'll try to make it for current release, but we could have a problem with best_practices. Will see.

**Comment by hurricup** [comment]
You may try current dev build 1.317: http://evstigneev.com/camelcade.jar

**Comment by nthykier** [comment]
Alexandr Evstigneev:
> You may try current dev build 1.317: http://evstigneev.com/camelcade.jar
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/hurricup/Perl5-IDEA/issues/778#issuecomment-174187485
> 

Hi,

I would love to.  Have you signed it with a GPG key or is it available
from a HTTPS download etc.?

Thanks,
~Niels

**Comment by hurricup** [comment]
Just download jar from the link. And use install from disk in plugin settings panel.

**Comment by nthykier** [comment]
I tried the current release and it seems to work just fine.  Thanks. :)
