### ISSUE TITLE
Please recognise "_"

### ISSUE THREAD

**Issue by nthykier** [hurricup/Perl5-IDEA#779]
Hi,

Perl supports an "implicit" stat result variable called "_".  The intelliJ module flags it as an unresolvable subroutine.  An example code:

```perl
sub is_executable {
  my ($file) = @_;
  return 1 if -f $file and -x _;
  return 0
}
```
It would be nice if "_" was not flagged.

**Comment by hurricup** [comment]
Fixed in https://github.com/hurricup/Perl5-IDEA/issues/640 and should be available in current dev build (or next release)
