### ISSUE TITLE
Editor ignores unchecked option "Editor->General->Code Completion->Autopup...->Insert selected variant...

### ISSUE THREAD

**Issue by miralita** [hurricup/Perl5-IDEA#781]
My settings:
![image](https://cloud.githubusercontent.com/assets/1781558/12511526/f5679ccc-c122-11e5-839c-c3517c76130f.png)

For example, I have a package with generated sub "to" and explicit subs "to_json" and "to_xml". Auto-completion list for "$self->to" contains two items (to_json and to_xml) and "to_json" inserts automatically by typing "(", so I have to press "ctrl + z" after completion or "Esc" before "(" every time. It is very annoying.

Expected behavior: selected variant doesn't insert automatically while option "Insert selected variant by typing dot, space, etc." is unchecked.

**Comment by hurricup** [comment]
Please, try current dev build and let me know if the problem persists: http://evstigneev.com/camelcade.jar

**Comment by miralita** [comment]
The problem is gone, thanx!
