### ISSUE TITLE
Project Structure is crashed if Perl SDK was moved.

### ISSUE THREAD

**Issue by almirus** [hurricup/Perl5-IDEA#801]
If delete or move strawberry dir and after opening Project Structure the system crashes.
[log.txt](https://github.com/hurricup/Perl5-IDEA/files/104906/log.txt)

**Comment by hurricup** [comment]
That's what happened :) Seen your automatic reports, but couldn't reproduce :) Thanks, i'll check it.

**Comment by almirus** [comment]
Добрый день. Лог сформировала idea, ошибка возникает если просто удалить
папку с perl или перенести в другое место без предварительной перенастройки
пути в разделе sdk.
Idea последней версии. Ошибка возникает даже если открыт не perl проект.
Спасибо за плагин.
26 янв 2016 г. 16:12 пользователь "Alexandr Evstigneev" <
notifications@github.com> написал:
