### ISSUE TITLE
[question] support for creating a camelcade / perl project

### ISSUE THREAD

**Issue by kotoroshinoto** [hurricup/Perl5-IDEA#83]
can we define a project type that KNOWS to use perl, or is it currently only used when a perl file is opened?

**Comment by hurricup** [comment]
Here is the answer from JetBrains I've answered few weeks ago: https://devnet.jetbrains.com/message/5542928#5542928

So there is no such thing as project type, but it's possible to make some gui for perl projects. Atm i'm working on language itself, will do this later.

Atm you just need to create an empty project and add module or modules.

**Comment by kotoroshinoto** [comment]
what do you mean by "add module or modules" ? I don't actually SEE a camelcade or perl module under new modules.

**Comment by hurricup** [comment]
Using these for now myself: 

http://joxi.ru/Q2KnlWbFo3gBmj.png
http://joxi.ru/RmzX1RnunQGQAO.png

**Comment by hurricup** [comment]
Done
