### ISSUE TITLE
Child indent is incorrect in comma-sequence with arrow commas

### ISSUE THREAD

**Issue by miralita** [hurricup/Perl5-IDEA#845]
For example, I have a subroutine with "named" arguments:
```
sub test {
	my %opts = (
		key1 => undef,
		key2 => undef,
		key3 => undef,
		@_
	);
}
```
When I add new keys to the end of the hash, everything is OK. But if I add the key inside the hash, then there is an additional indentation:
```
sub test {
	my %opts = (
		key1 => undef,
		key2 => undef,
		     key2_1 => 'EXTRA INDENT!!!',
		key3 => undef,
		@_
	);
}
```
Expected behavior: new line should be indented on the same level as previous line.

**Comment by hurricup** [comment]
re-formatting helps, but i've got the problem. Thanks.

**Comment by hurricup** [comment]
You may try http://evstigneev.com/IDEA-Perl5-1.339.zip

**Comment by miralita** [comment]
Everything is OK now, thanx!
