### ISSUE TITLE
Language Injections not compatible with interpolation in here-doc?

### ISSUE THREAD

**Issue by StrikeForceZero** [hurricup/Perl5-IDEA#854]
I couldn't find an issue covering this so forgive me if it was brought up before.
The language injections via HERE-DOC only seem to work without `$`'s or else it treats the entire block as a string without language injections..

a. using single qouted limit strings ignores perl variable interpolation. (as expected)
b. using double quoted limit strings
 * will allow language injection as long as their are no `$` 
 * the `$` is escaped with a `\` (which stores unwanted `\`'s)

c. using bareword or underscored limit strings (same as B)

#### Example A

```perl
my $html = <<'HEREDOC';
<script>
//I'm interpreted as javascript with html language injected
//$ is left alone
</script>
HEREDOC
```

#### Example B

```perl
my $html = <<"HEREDOC";
<script>
//I'm interpreted as javascript with html language injected
//$ is interpolated and language injections breaks reverting this here-doc section to act like a string in the editor
</script>
HEREDOC
```
#### Example C

```perl
my $html = <<__HEREDOC__;
<script>
//I'm interpreted as javascript with html language injected
//$ is interpolated and language injections breaks reverting this here-doc section to act like a string in the editor
</script>
__HEREDOC__
```

using intellij 15.03 and CamelCade version 1.333

**Comment by hurricup** [comment]
This has been done intentionally, helps in some cases, like mysql. But, seems it should be configurable.
And it looks like interpolation bug, cause sigil should not have space after it in interpolated code if i remember right.
Thank you for report.

**Comment by StrikeForceZero** [comment]
```perl
my $foo = 'bar';

print <<'HEREDOC';
<body>$foo</body>
HEREDOC

print <<"HEREDOC";
<body>$foo</body>
HEREDOC

print <<HEREDOC;
<body>$foo</body>
HEREDOC
```

##### output

```html
<body>$foo</body>
<body>bar</body>
<body>bar</body>
```

##### editor (before language injections)

![image](https://cloud.githubusercontent.com/assets/983413/13292069/6080d1fc-dae8-11e5-93e7-09254ed4eb0c.png)

##### editor (after language injections)

![image](https://cloud.githubusercontent.com/assets/983413/13292124/8bdc5ba0-dae8-11e5-8ed0-0a3185081fe1.png)

##### editor - double quotes and barewood only offer language injections without '$'

![image](https://cloud.githubusercontent.com/assets/983413/13292177/aeee3f96-dae8-11e5-8705-9fbff5336685.png)

![image](https://cloud.githubusercontent.com/assets/983413/13292195/c2798872-dae8-11e5-96a8-fb956b9857f8.png)

##### alt+enter does not offer language injections with '$' present

![image](https://cloud.githubusercontent.com/assets/983413/13292233/f48a757e-dae8-11e5-8d36-9c270613dc1a.png)

**Comment by hurricup** [comment]
I'll post here a link to the daily build with this change.

**Comment by hurricup** [comment]
You may try http://evstigneev.com/IDEA-Perl5-1.338.zip

**Comment by StrikeForceZero** [comment]
Awesome. Injections work with interpolated here-doc blocks now.

Unfortunately, there seems to be a regression breaking all language injections in a perl file, see below.
(the first tag has to be escaped `\` for the html to be parsed and syntaxed highlighted properly)

![image](https://cloud.githubusercontent.com/assets/983413/13298519/042d8bd0-db05-11e5-9930-65f64654b43e.png)

**Comment by hurricup** [comment]
Oh, i see. I'm mostly using marker-based injections, not manual. Try to use HTML marker text instead of default HEREDOC. But i'll check this one right now.

**Comment by hurricup** [comment]
Re-download the archive from the same link. And install it. Should work fine now even with manual injections. Thanks again!

**Comment by StrikeForceZero** [comment]
Fixed. Thanks a lot. This really helps!
