### ISSUE TITLE
PhpStorm "forgets" configured libraries after restart

### ISSUE THREAD

**Issue by angileriDE** [hurricup/Perl5-IDEA#858]
I have added 2 content root folders in my project, visible in "_Project: <project-name>_" -> "_Perl5 libs_", and configured my library directories. Unfortunately PhpStorm does not store the libraries of the 2nd content root folder permanently. After a restart I have to configure the libraries of the 2nd content root folder again.

Versions:
PhpStorm 10.0.3
Perl5 Support 1.333
Ubuntu 15.10

**Comment by hurricup** [comment]
This a flaw of current roots system. You shouldn't mark same folder as source in native projects's structure and as lib in perl's structure. Someone will overwrite other's results. Just perl's lib as lib and that's all. Please, try it and lemme know if it helped.

**Comment by angileriDE** [comment]
Sorry, but I don't get it. 
In order to select some sources as library I have to add the folder as content root, do I?

**Comment by hurricup** [comment]
First you go to project structucture and mark dirctories there. Than click ok/apply.
After that you may go to Perl5 libs and mark lib dirs there. Than click ok/apply.
Same dir can't be marked as source in project structure and as lib in perl5 libs. Only the last.

**Comment by angileriDE** [comment]
OK, got it! thx
