### ISSUE TITLE
Figure out some marker for automatic injections to the regular strings

### ISSUE THREAD

**Issue by hurricup** [hurricup/Perl5-IDEA#860]
Is something like:
```
my $somevar = '<body></body>'; # HTML
```
will be enough?

**Comment by StrikeForceZero** [comment]
I like it, but it could be a good idea to make it a little more specific.

An example in php; one could disable inspections by writing:

```php
/** @noinspection PhpUndefinedClassInspection */
```

All ide hints in php were using `@[type]` inside a block comment. Unfortunately perl doesn't have a block comment other than POD.

intellij java's look like `//noinspection unchecked` and `@SuppressWarnings("unchecked")`

maybe something like `# @inject HTML` so you can have more extendability / standard with future inline comments

for example at the top of a file `# @inject off` could disable auto injections for the entire file.

or maybe in the future we have type hinting by `# @type integer $someScalar` `# @type Array<DBH> $someScalar` (wishful thinking from a spoiled developer :p)

Just showing some possible use cases. 


sidenote: I noticed the editor highlights `#@` yellow and offers to language inject the comment?

![image](https://cloud.githubusercontent.com/assets/983413/13401927/0b703e1c-dedc-11e5-81bc-ba96da962306.png)

![image](https://cloud.githubusercontent.com/assets/983413/13401934/1725347e-dedc-11e5-9670-2605f2817501.png)

not sure if thats a bug and needs an issue opened

**Comment by hurricup** [comment]
I like the idea of `#@inject` annotation. Something like
```
my ($sql, $html) = 
   ("SELECT UNIX_TIMESTAMP", #@inject MYSQL
  "<BODY><HEAD></HEAD></BODY>"); #@inject HTML

# and per statement/subtree like 

#@inject MYSQL
my ($query1, $query2) = (
 'SELECT ....',
 'SELECT ... '
);

**Comment by hurricup** [comment]
blocked by #891
