### ISSUE TITLE
Implement #@class annotation

### ISSUE THREAD

**Issue by xic8hix** [hurricup/Perl5-IDEA#868]
`sub test {`
`#@class Class::Foo`
`my $self = shift;`
`}`
 analogue "#@return" for variables only

**Comment by hurricup** [comment]
What for? There is a pretty standard perl syntax:
```
my Class::Foo $somevar;

**Comment by xic8hix** [comment]
edited first comment, code was distorted.

**Comment by xic8hix** [comment]
i'm using Mojolicious, Mojo have "has" and default subroutines, example - "startup", and often i have unknown variables

**Comment by hurricup** [comment]
Still not sure what are you trying to achieve, in your example it works just fine: 
```
sub test{
  my Class::Foo $self = shift;
}
```
Also, if this test will be in some package, self's type should be detected automatically.
Guess we need more enchanced example.

**Comment by xic8hix** [comment]
Yes, You are right! Thx
