### ISSUE TITLE
Implement NamesValidator for rename refactoring

### ISSUE THREAD

**Issue by hurricup** [hurricup/Perl5-IDEA#94]

**Comment by magnuskiro** [comment]
Is this related to refactoring/renaming of variables in strings?

Where, in the case of: {
my $var = "something";
my $string = "var is $var";
},
renaming(with the inbuild shift+F6 function) $var to $newvar, will only change the variable declaration and not the use of the variable in the string? 
resulting in this: {
my $newvar = "something";
my $string = "var is $var";
}

**Comment by hurricup** [comment]
Nope, it's related to interpolation #248 and #249.
Please, check https://github.com/hurricup/Perl5-IDEA/wiki/Known-issues

**Comment by hurricup** [comment]
Fixed in 1.2
